apiVersion: v1
kind: Service
metadata:
  name: llama-chatbot
spec:
  selector:
    app: llama-chatbot
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours 